name: Report a Docs Issue
description: Is something wrong, confusing or missing in the docs?
labels:
  - 'type: documentation'
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a docs issue report!

  - type: textarea
    id: describe
    attributes:
      label: Describe the Documentation Issue
      placeholder: Describe the issue you encountered and suggest your updates.
    validations:
      required: true

  - type: textarea
    id: section
    attributes:
      label: Specific Section of Documentation
      placeholder: Indicate which part of the documentation needs improvement.
    validations:
      required: true

  - type: textarea
    id: clarity
    attributes:
      label: Request for Clarification
      placeholder: Specify what you believe needs clarification.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I Agree to Follow This Project's Code of Conduct
          required: true
