name: Request a Feature
description: Do you want to suggest a new feature?
labels:
  - 'type: feature'
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to request a feature!

  - type: textarea
    id: describe
    attributes:
      label: Describe what problem you're trying to solve?
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I Agree to Follow This Project's Code of Conduct
          required: true
