name: Request a Feature
description: Do you want to suggest a new feature?
labels:
  - 'type: feature'
assignees:
  - nikkeyl

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to request a feature!

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: What are the benefits of this feature?
    validations:
      required: true

  - type: textarea
    id: drawbacks
    attributes:
      label: Are there any potential considerations we should know about?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I Agree to Follow This Project's Code of Conduct
          required: true
