name: Remark

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
  push:
    branches:
      - main
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  remark:
    name: Remark

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set Up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6

      - name: Install Dependencies
        run: bun ci

      - name: Lint
        run: bun remark . --quiet --frail
